modLoader="lowcodefml"
loaderVersion="[56,)"
license="MIT"

[[mods]]
modId="better_craftables"
version="5.4.0-beta"
displayName="Better Craftables"
logoFile="pack.png"
displayURL="https://modrinth.com/datapack/better-craftables"
credits="https://github.com/Classic36-Media/Better-Craftables/wiki/Credits"
authors="Classic36"
description="Adds some quality-of-life crafting and smelting recipes to the game."

[[dependencies.better_craftables]]
    modId="forge"
    mandatory=true
    versionRange="[56,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.better_craftables]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.6,1.21.8]"
    ordering="AFTER"
    side="BOTH"