modLoader="lowcodefml"
loaderVersion="[55,)"
license="MIT"

[[mods]]
modId="better_craftables"
version="4.1.0"
displayName="Better Craftables"
logoFile="pack.png"
displayURL="https://modrinth.com/datapack/better-craftables"
credits="https://github.com/Classic36-Media/Better-Craftables/wiki/Credits"
authors="Classic36"
description="Adds some better crafting recipes to Minecraft!"

[[dependencies.better_craftables]]
    modId="forge"
    mandatory=true
    versionRange="[55,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.better_craftables]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,)"
    ordering="AFTER"
    side="BOTH"